### ISSUE TITLE
Vivian and Aliya Final Sprint

### ISSUE THREAD

**Issue by vivianknee** [Codemaxxers/Issues#81]
# Objective
The objective of this final sprint and feature addition is to tie the cyber games and fight games together and give them both an equal level of purpose. Currently, the cyber games are very separate from the rest of the game, thus by integrating the cybergames into the general leaderboard and creating incentives to play them by including powerups and keys, the player is more inclined to play every game and feature of the project thus better integrating the two games (Cyber and fight).

# Tasks
- [x] NEW IDEA/Feature: Create a key system to better integrate cyber games with fight game
- If a user plays a certain number of cyber games --> keys are unlocked on the home page map that can be collected --> these keys can give the users character powerups to use in the fights (skip a question, get a hint, etc) 
- Key features will be deployed in order to be presented 
- Multiple people will be able to interact with the feature (collect keys) at the same time, data updates

## The Plan
**Requirements**:
- [x] A key system on the home page map.
- [x] A mechanism to convert keys into power-ups for use in the fighting game.

 **Game Data Integration**:
- [x] Ensure that both the cyber games and fighting game share a common user database.
- [x] Implement a tracking mechanism to record the number of cyber games played by each user.

**Key System**:
- [x] Create a key interface on the home page map.
- [x] Define conditions for key unlocking (e.g., number of games played).
- [x] Design the key as an item that appears on the menu bar)

**Power-Up Mechanism**:
- [x] Define the power-ups (e.g., skip a question, get a hint).
- [x] Implement a system to get keys for power-ups in the fighting game.

**Database Schema**:
- [x] Add a `games_played` field to the user database to track the number of cyber games played.
- [x] Add a `keys_collected` field to track the number of keys a user has.

### **Monday:** Share plan with team and create ideation visuals. Ensure that key requirements for N@TM are distributed across features for all team members
<img width="617" alt="Screenshot 2024-05-21 at 11 17 28 AM" src="https://github.com/Codemaxxers/Issues/assets/82780605/f446baf8-a7dc-42f8-91db-0dacd83da65b">
<img width="613" alt="Screenshot 2024-05-21 at 11 17 43 AM" src="https://github.com/Codemaxxers/Issues/assets/82780605/29675ae0-eb21-4f77-872d-da24cb39fc9c">
<img width="621" alt="Screenshot 2024-05-21 at 11 17 53 AM" src="https://github.com/Codemaxxers/Issues/assets/82780605/fb82343b-fbf9-49a7-b3f5-c9e8d2c7776d">
<img width="652" alt="Screen Shot 2024-05-21 at 11 18 59 AM" src="https://github.com/Codemaxxers/Issues/assets/111466919/00c06042-f94b-4f21-989c-f12812ef279b">
<img width="691" alt="Screen Shot 2024-05-21 at 11 17 51 AM" src="https://github.com/Codemaxxers/Issues/assets/111466919/9852da2b-dfbf-40ea-b1c1-4c520c187ddc">

### **Wednesday:** Work on database with 'gamesPlayed' and 'keysCollected' to create a system that awards powerups based on plays of cyber game
1. GET requests to display number of keys based on the column `keysCollected` in the person database on the backend
- here it is for the fight scene
<img width="1252" alt="PNG image" src="https://github.com/Codemaxxers/Issues/assets/82780605/98f45fc0-7769-4717-8389-d4cd0732693b">

- here it is on the main game page
<img width="534" alt="PNG image" src="https://github.com/Codemaxxers/Issues/assets/82780605/6bf07248-78eb-499b-a6b7-c1d02add5bb8">

- code:
<img width="791" alt="Screenshot 2024-05-26 at 6 06 43 PM" src="https://github.com/Codemaxxers/Issues/assets/82780605/c9524eb4-e5d9-4dee-ae9e-d3442b7f7253">

2. POST requests to increase number of plays by 1 each time AND to add/remove keys based on thresholds
- post request working in console log to increase game plays by 1 after playing password game
<img width="1432" alt="Screenshot 2024-05-26 at 6 03 47 PM" src="https://github.com/Codemaxxers/Issues/assets/82780605/c443dd7e-eaca-4a28-a135-adfc8b3b05b3">

- post request to add keys
<img width="611" alt="Screenshot 2024-05-27 at 11 52 27 AM" src="https://github.com/Codemaxxers/Issues/assets/82780605/63c49bad-7517-4e5e-abb7-ab3ea03a0f17">

- proof that key amount is updated on backend
<img width="981" alt="Screenshot 2024-05-27 at 11 53 19 AM" src="https://github.com/Codemaxxers/Issues/assets/82780605/9261020c-33d8-439e-b07a-28e293df1f4a">

- post request to remove keys
<img width="585" alt="Screenshot 2024-05-27 at 12 09 29 PM" src="https://github.com/Codemaxxers/Issues/assets/82780605/eaff0f9d-93ee-4404-b365-9d99c433a6f7">

- post request to reset game plays for players to earn multiple keys
<img width="614" alt="Screenshot 2024-05-27 at 12 40 00 PM" src="https://github.com/Codemaxxers/Issues/assets/82780605/f04fa76a-1ae3-46f2-969e-7233ba12f02d">

### **Thursday:** Implement the function of the powerups and ensure they work in the fight game
1. powerups
- options popup (wow looks so much like the canva one)
<img width="935" alt="Screen Shot 2024-05-27 at 12 49 56 PM" src="https://github.com/Codemaxxers/Issues/assets/111466919/43df5a3e-326d-48cb-bd58-0ff258ea117b">
- functions for each powerup
<img width="695" alt="Screen Shot 2024-05-27 at 10 27 19 PM" src="https://github.com/Codemaxxers/Issues/assets/111466919/28d5b94c-5163-44d8-ad25-532c1fc9766b">
<img width="544" alt="Screen Shot 2024-05-27 at 10 28 28 PM" src="https://github.com/Codemaxxers/Issues/assets/111466919/a7a9b3d2-3c6a-45f0-a8eb-e7042fc0796e">

- showcase of the hint appearing after using a key. however, the questions database is currently undefined 
<img width="1051" alt="Screenshot 2024-05-28 at 11 24 47 PM" src="https://github.com/Codemaxxers/Issues/assets/82780605/140226c2-ac42-4b15-b058-fa8382dbc9f8">

- added hints to backend question database
<img width="899" alt="Screenshot 2024-05-27 at 10 26 35 PM" src="https://github.com/Codemaxxers/Issues/assets/82780605/237f0d64-c98f-44a2-8811-ac3c9ffeb5ec">

Finishing touches:
- Make use key button only visible when player has keys
- Make key post requests work for every game
- When powerup option is used, have a visual on appear on screen (ex: when player uses skip, have a "Question Skipped" appear on screen)
- When key is earned, have a visual on appear on screen (ex: "You just earned a key. You can use it for a powerup in the fight game!)
