### ISSUE TITLE
Finn Project Check Plan

### ISSUE THREAD

**Issue by F1nnC** [Codemaxxers/Issues#82]
## Main Focus

To finalize the fighting mechanic with animations and combine my feature with Theo's inventory database to create new attacks. Right now the attack moves are just hard-coded moves that don't scale with the enemy or the player. They have been the same since the start and I want to be able to scrap the system altogether and base it on the weapon equipped. Implementing both databases and creating new animations for the weapons, should show collaboration (between me and Theo) and also have some new code to polish the fighting sequence. 

## Tasks

- [x] Remove old fighting attacks
- [x] Create new move dynamically through the weapon equipped in the backend
- [x] Change the enemy database to scale enemy health better
- [x] Change the questions database so less ChatGPT questions
- [x] Create player vs player fighting wireframe for theo

### Mon-Tue
- [x] Meet with Theo to learn how the inventory works better
- [x] Complete task 1
- [x] Complete task 2

### Tue-Thu

- [x] Change how inventory works (refetch instead refresh page)
- [x] Complete Wirfeframe for player vs player

### Thu-Fri

- [x] Clean up question-answering system
- [x] Clean up question database (good questions)
- [ ] Create a system to switch between CSP and CSA questions

### Weekend
- Depending on me and Rachit schedule, most likely a Panera code code code day
- [ ] Fighting with Rachit webhooks
- [ ] People battle each other

## Demo/Proof of completion
- Github Commits
- Live Demo
- Terminal showing request to the backend
- Check Box Clicked
