### ISSUE TITLE
Rachit Final Checkpoint Plan

### ISSUE THREAD

**Issue by rachit-j** [Codemaxxers/Issues#84]
## Objective
The objective of this sprint is to finish websockets (which just need the correct APIs and methods) and then to document the websockets and write them in nodejs, python, and java with extensive documentation. As of now, I have been focused and dedicated to making websockets work, especially through Nginx and many other protocols (the amount of stackOverflow reading I had to do for this...). Currently, websockets are not being utilized since multiplayer has not been developed yet, however, as multiplayer develops, websockets will be utilized more and more. 

## Tasks

- [x] Figure out what API's websockets need
- [x] Write Documentation for websockets
- [x] Complete a demo and documentation for Java Websockets
- [x] Complete a demo and documentation for Python Websockets
- [x] Complete a demo and documentation for Nodejs Websockets

## Plan

**Requirements**

- POSTMAN
- Keyboard
- Research (already completed)

**On Codemaxxers**

- [x] Get API List
- [x] Program APIs
- [x] Document formatting for APIs
- [x] KEY SPLITTING and logging documentation

Integration is with the feature (that is literally what its for)

**On Java Demo**

- [x] Simplify CodemaxxerConnections
- [x] Write README
- [x] Copy Nginx Configurations

**On Nodejs Demo**

- [x] Figure out how to make it not go through localhost (_really Mr. Mortensen_)
- [x] Create new Nodejs repo
- [x] Deploy a tester for it (try going through vercel first for easier logging)
- [x] Write README
- [x] Write Nginx configurations

**On Python Demo**

- [x] Learn how to use flask
- [x] Research python websocket stuff
- [x] Make an API for python websockets
- [x] yipeee test it
- [x] Write a README and Nginx configurations

## Schedule

**Monday**

- Ask what multiplayer needs from websockets
- Write documentation for codemaxxer websockets and key splitting

**Tuesday**

- Create blog/repo for Java. 
- Finish Java tasks
- Test Java

**Wednesday**

- Create blog/repo for Nodejs. 
- Finish Nodejs tasks
- Test Nodejs

**Thursday**
- Flask research day
- Learn how to use and create a flask starter
- Start on python tasks

**Friday**
- Finish creating blog/repo for Nodejs. 
- Finish python tasks
- Test python
- Wrap up everything in a nice blog

According to this plan, everything shall be done and ready to go by Friday. 

## Milestones

- [x] COMPLETELY WRAP UP CODEMAXXERS (NO ONE SHOULD NEED TO ASK ME FOR WEBSOCKETS I THINK THIS IS ALMOST DONE) Due monday
- [x] Finish Java documentation for websockets due tuesday
- [x] Finish Nodejs documentation for websockets due wednesday
- [x] Finish python documentatiojn for websockets due friday
- [x] Finish blog with everything for presentation due friday

## Presentation plan

**Stage 1: Codemaxxers**

- Present all sum of work in codemaxxers
- Dedicate 7-8% of time to websockets and more to multiplayer
- Live Demo through postman since it may not seem obvious through gameplay (will still demo gameplay)

**Stage 2: Explanations**

- Talk about design process, successes and failures, thousands of webpages of research (AGAIN SHOUTOUT TO STACKOVERFLOW)
- Describe integration and purpose (not too hard, literally built for integration)
- Describe protocols and structures, from each layer of the web
- Describe the simplified usage and applications
- Show the keyhandler and talk about creating your own websocket interface with own commands.
- Show movement from initial github commits to codemaxxers to more web based testing (since the protocol is simple enough, but every layer, such as nginx, has to wrap it, which is why I may not have too many commits nearing the end)

**Stage 3 (part of stage 1): Demo**

- Demo websockets with sample commands in keyhandler
- Demo working multiplayer

**Stage 4: Wrapup**

- Make sure to hit all checkboxes
- Get over 6 hours of sleep
- Archive and preserve project

## Documentation and pictures

Documentation should look like this:

<img width="1428" alt="image" src="https://github.com/Codemaxxers/Issues/assets/56803677/a15ffebb-c0c6-4fd1-99b1-752be0e88655">

Work and analysis should look like this:

<img width="1371" alt="image" src="https://github.com/Codemaxxers/Issues/assets/56803677/8170e9fc-cf7c-4c91-81f9-51fc6d4e11f6">

Make sure to include all files:

<img width="844" alt="image" src="https://github.com/Codemaxxers/Issues/assets/56803677/0f0b924f-6ece-4b84-bcc2-591843ddf363">

Make sure to have some humor:

<img width="596" alt="image" src="https://github.com/Codemaxxers/Issues/assets/56803677/f0d02897-235a-424e-8693-1818054a2b24">

**Comment by rachit-j** [comment]
# Day 1 Websocket Documentation

https://codemaxxers.github.io/codemaxxerblog/2024/05/20/Websocket-documentation.html

**Comment by rachit-j** [comment]
## Day 2 Java Websockets

https://github.com/Codemaxxers/Java-Websockets

**Comment by rachit-j** [comment]
# Day 3 Nodejs Websockets

[https://codemaxxers.github.io/codemaxxerblog/2024/05/22/Nodejs-Websocket-Documentation.html](https://codemaxxers.github.io/codemaxxerblog/2024/05/22/Nodejs-Websocket-Documentation.html)

**Comment by rachit-j** [comment]
# Day 4-5 Python Websockets

https://github.com/Codemaxxers/websocket-python

**Comment by rachit-j** [comment]
# Final Blog

[https://codemaxxers.github.io/codemaxxerblog/2024/05/29/Websocket-Documentation-complete.html](https://codemaxxers.github.io/codemaxxerblog/2024/05/29/Websocket-Documentation-complete.html)
