### ISSUE TITLE
Grace and Emma Final Checkpoint Plan

### ISSUE THREAD

**Issue by gwang1224** [Codemaxxers/Issues#85]
## Main Focus 👁️

To finalize cyber game and connect them to the rest of the game. All games are functional but not fully connected to the rest of the map. We aim to improve user experience and overall playability of the games by fixing the styling and adding additional features that would allow the user to easily understand and learn computer science concepts.

## Tasks !!!!

- [x] Gravity game: make text readable✅, adjust speed ✅, make terms not overlap✅, fix so terms don't get cut off on the right✅, when press close the game freezes and resumes once click on game again✅
- [x] Fix styling to make 3 games appear on computer screen 
- [x] Password game: buttons not working when press✅, make buttons appear on screen no matter size of email text✅, fix why after reset the check button doesn't work anymore✅
- [x] Reset button for each game so user can play multiple times to get more points 
- [x] Make play cyber games button available on bottom menu 
- [x] Gravity game: Connect backend database to frontend gravity game so terms are randomized✅, changed terms to be categorized by csa, csp, and cyber✅
- [ ] Integrate new gravity game background into comp screen, reset button, close button, back buttons
- [ ] Fix positioning for elements so pop up fits and doesn't move on all screen sizes 

### Mon-Tue: Discussion & Design Plan
- [x] Talk with map people (Luna, Vivian, Aliya, etc) about connecting cyber house to main map 
- [x] Fix CORS error for connecting backend and frontend in gravity game
- [x] <b>Checkpoint</b>: Present styling transformation plan to rest of P1 & P3 team for approval 

### Wed-Friday: Styling & User experience 
- [x] Cyber house and main map connected 
- [x] Fix styling of cyber games based on previous days plan
- [x] Create better terms in the terms database

### Weekend: Finish & Collect Feedback
- [x] Finalize all tasks 
- [x] Collect feedback on UI/UX and implement improvements 
- [x] <b>Checkpoint</b>: everyone knowledgeable of each other's work and what need to do moving forward

## Demo/Proof of completion 👍
- Github Commits
- Live Demo: character entering from main map to cyber house --> playing each of three games, tutorial for first time users 
- Check Box Clicked

## Styling before ⬅️

Gravity:
<img width="1439" alt="Screenshot 2024-05-20 at 12 12 30 PM" src="https://github.com/Codemaxxers/Issues/assets/94924172/bf968b73-95db-4369-b883-c135010680d3">

Ideal finish 
<img width="694" alt="Screenshot 2024-05-20 at 12 13 03 PM" src="https://github.com/Codemaxxers/Issues/assets/94924172/ac4ccf12-74a2-4dc0-940a-288886d69fed">

Password:
<img width="1440" alt="Screenshot 2024-05-20 at 12 14 10 PM" src="https://github.com/Codemaxxers/Issues/assets/94924172/5fb22816-3c61-4bfd-aac5-17446336a2d1">

Phishing:
<img width="1440" alt="Screenshot 2024-05-20 at 12 14 37 PM" src="https://github.com/Codemaxxers/Issues/assets/94924172/9dbbb7da-1a07-4be1-a36e-8e82c3ae7472">

## Styling after 
Gravity 

<img width="992" alt="image" src="https://github.com/Codemaxxers/Issues/assets/104966589/c66aacfe-43e1-41d1-9e72-6ecc931c4992">

**Comment by emmaxshen** [comment]
# Logging of Progress 

## Tuesday 
What we are starting off with: game buttons not in appropriate place
<img width="1345" alt="image" src="https://github.com/Codemaxxers/Issues/assets/104966589/9824f4cf-f90f-4618-847a-7c254342deb4">

After: Aliya found trick to keep game icons in place by putting invisible buttons on top of them and having that have a fixed position. Looks MUCH better

<img width="1468" alt="image" src="https://github.com/Codemaxxers/Issues/assets/104966589/62b0d376-91e8-4808-9084-254333960398">

## Wednesday 
<img width="1338" alt="image" src="https://github.com/Codemaxxers/Issues/assets/104966589/a281a39a-6bd5-4362-83a1-dedaf9de51b9">

- pop up window so that it looks like user is actually playing game on computer 

<img width="1344" alt="image" src="https://github.com/Codemaxxers/Issues/assets/104966589/f7be8cff-7530-4567-afb4-24ead60f9db2">

- aligned pop up with computer screen
- making game more enjoyable: text more readable, adjust speed of terms falling, make it so that terms don't overlap one another (see isOverlapping function below) 

<img width="678" alt="image" src="https://github.com/Codemaxxers/Issues/assets/104966589/6517b1f6-8965-4a98-b964-6dbe8d79cbb5">

## Thursday 
<img width="1459" alt="image" src="https://github.com/Codemaxxers/Issues/assets/104966589/cd41c6c2-ecb6-42a5-8c2a-5a4faaafff58">

- corner cases: fix so terms don't get cut off on the right (control random x position), when press close the game freezes and resumes once click on game again (used flags to control game state, skip drawing and game loop if paused and toggle game pause state if canvas is clicked once again)

<img width="709" alt="image" src="https://github.com/Codemaxxers/Issues/assets/104966589/18ec7840-413c-440d-b6ef-7690b9e0a9d3">
<img width="405" alt="image" src="https://github.com/Codemaxxers/Issues/assets/104966589/a6450567-3c37-417c-94f3-b62107a5192a">
<img width="456" alt="image" src="https://github.com/Codemaxxers/Issues/assets/104966589/3864a199-d734-4383-aa58-bd18719db51f">
<img width="573" alt="image" src="https://github.com/Codemaxxers/Issues/assets/104966589/cf40881d-829b-4179-ac04-0a7b10ee94f9">

## Friday 

- make phishing attack game and password game appears on comp screen 

<img width="1470" alt="image" src="https://github.com/Codemaxxers/Issues/assets/104966589/9ffefbf0-7a23-40fc-853b-9bf814011c77">
<img width="1459" alt="image" src="https://github.com/Codemaxxers/Issues/assets/104966589/192baa68-3415-4934-bba6-fa3edb55b2d1">

## Sunday 

- fix phishing email attack game so that it actually works when user presses phishing or legitimate button 
- DOMContentLoaded Event: ensures the script runs only after the DOM is fully loaded to prevent issues with elements not being found
- event Listeners: attached to buttons after the DOM is ready to ensure they exist when the script is executed

<img width="645" alt="image" src="https://github.com/Codemaxxers/Issues/assets/104966589/c0c9ae66-0e39-4b01-8515-bddfbcec1f7b">
<img width="698" alt="image" src="https://github.com/Codemaxxers/Issues/assets/104966589/773e9c91-1c74-430b-b00b-08f547580659">

- added reset button to every game so that user can play multiple times to accumulate points 

<img width="231" alt="image" src="https://github.com/Codemaxxers/Issues/assets/104966589/76f3d75a-144b-4b31-9dd1-7752a3ff5e59">

## Monday 

<img width="251" alt="image" src="https://github.com/Codemaxxers/Issues/assets/104966589/749c9d12-5c19-4d2a-ad11-d6fe10726bd7">

- enter cyber house button on menu (always accessible)

**Comment by gwang1224** [comment]
## Tuesday

- Created pixel art for gravity backend
- Attempted to implement backend for the game

<img width="889" alt="Screenshot 2024-05-27 at 11 32 59 PM" src="https://github.com/Codemaxxers/Issues/assets/94924172/7cfceb84-b70c-48da-b8a8-78ad5e0b0b2a">


## Thursday/Friday

Status of Gravity: Ugly and doesn't use backend
<img width="798" alt="Screenshot 2024-05-27 at 11 27 27 PM" src="https://github.com/Codemaxxers/Issues/assets/94924172/dda61ef4-faf9-4254-801a-61c29ff99a20">

[Commit](https://github.com/Codemaxxers/codemaxxerFrontend/commit/555977db5d3f679aad072e1a7eb8a955f14882ec)

Status by end: 
- Gravity is still ugly but has a nice background
- Backend is connected and function is created that calls backend everytime a new term pops up on screen
- Only applicable for CSP terms at the moment

<img width="655" alt="Screenshot 2024-05-27 at 11 30 54 PM" src="https://github.com/Codemaxxers/Issues/assets/94924172/ac62eddc-3632-42fa-b8c5-31b3c7056062">

<img width="352" alt="Screenshot 2024-05-27 at 11 31 18 PM" src="https://github.com/Codemaxxers/Issues/assets/94924172/e6a40ddf-e780-4f7a-9fc1-9da573a7ef4f">

<img width="1318" alt="Screenshot 2024-05-27 at 11 38 39 PM" src="https://github.com/Codemaxxers/Issues/assets/94924172/e799ab7b-fb2c-42a0-8ba8-718c68f547fb">

- New start page
- initially was going to make 3 separate pages for csp, csa, and cyber, but then realized a button that allows the user to select and then use that input to call the backend would be a lot easier

<img width="590" alt="Screenshot 2024-05-27 at 11 39 11 PM" src="https://github.com/Codemaxxers/Issues/assets/94924172/1959ab10-f652-4b34-864d-f442ff439f04">

<img width="501" alt="Screenshot 2024-05-27 at 11 40 18 PM" src="https://github.com/Codemaxxers/Issues/assets/94924172/abacadbb-3fde-46e1-9b62-88caa3ca1818">

<img width="743" alt="Screenshot 2024-05-27 at 11 41 14 PM" src="https://github.com/Codemaxxers/Issues/assets/94924172/45c9176b-4548-4cbf-b06c-027a2685dd82">

<img width="490" alt="Screenshot 2024-05-27 at 11 42 11 PM" src="https://github.com/Codemaxxers/Issues/assets/94924172/9f7ce0b4-3247-4f18-a8fa-ffaf2021f498">


- start button for each of the games (CSA, CSP, Cyber)
- modified function to include parameter for what game is played

## Weekend

- final styling
- making everything work on deployed

realized that window size was not full screen because it did not take the entire window width
<img width="1440" alt="Screenshot 2024-05-27 at 11 43 19 PM" src="https://github.com/Codemaxxers/Issues/assets/94924172/2a7b1bb8-c5ec-4799-9247-4d0fed8039eb">

made canvas size a variable so that it would be applicable for all screen sizes
<img width="427" alt="Screenshot 2024-05-27 at 11 44 36 PM" src="https://github.com/Codemaxxers/Issues/assets/94924172/68a6f263-66fb-4e32-8ed4-28ade03de8cb">


- attempted to put the gravity game on the computer screen but somehow changed the background for the password and phishing games as well
- ended up just linking game because the computer screen is too small for the game anyway and full screen seems better for use experience

updated backend with easier terms because people said it was too hard
<img width="1001" alt="Screenshot 2024-05-27 at 11 49 07 PM" src="https://github.com/Codemaxxers/Issues/assets/94924172/c50be9ad-2829-4a76-9a5f-88ff8fcc59e1">


End game
<img width="1395" alt="Screenshot 2024-05-29 at 10 04 01 AM" src="https://github.com/Codemaxxers/Issues/assets/94924172/47f7de59-0465-41c3-b9e1-dd41720c26ba">
