### ISSUE TITLE
# Final Sprint - Theo Huntalas

### ISSUE THREAD

**Issue by TheoH32** [Codemaxxers/Issues#86]
# Plan
Use Rachits websockets to implement a multiplayer feature in our game

# Tasks
- [ ] Make frontend for two player fight
- [ ] Get user info of both players on both screens
- [ ] Make fight work with commands

# Schedule

## Monday

- [x] Read Rachits documentation and plan out work

## Tuesday

- [ ] Finish frontend for websocket integration

## Wednesday

- [ ] Get simultaneous player connection and report to Rachit for additional endpoints needed

## Thursday

- [ ] Figure out how to use websockets for players to "fight" each other

## Friday

- [ ] Clean up features

**Comment by TheoH32** [comment]
# Daily Work Log

---------------------------------------------------------------------
## [Monday](https://github.com/Codemaxxers/codemaxxerConnections/commit/94cb253387247567e7899d5305361c0b7f72309d)
https://github.com/Codemaxxers/Issues/assets/47646488/a3875398-5a0e-492d-a9b0-e6cf7d3e9208
- Made "register" command for player 1 and 2 creation with custom stats
- Made "attack" command which takes first listed player damage and minus second listed player health
- Commited and updated locally

### Stuff that needs to be done
- [ ] how to add multiple lobbys? (maybe add more endpoints than /myhandler, like /lobby1 but need 2 person limit)
- [ ] add error handling
---------------------------------------------------------------------
## Tuesday
![IMG_9582-min](https://github.com/Codemaxxers/Issues/assets/47646488/dbafd4d4-929d-4e86-be37-730e357396b1)
![IMG_9584-min](https://github.com/Codemaxxers/Issues/assets/47646488/bb457122-b5e0-4ab2-a7f3-fb5ad322c6dc)

Today I worked a lot on ideation and structure of how exactly the multiplayer aspect will work. Lobbys in how players connect was the biggest mental obstacle to get around.
1. Decide between static and dynamic lobbys ----> chose dynamic for scaling and a challenge
2. Processed how user interaction will work between creating and joining lobby
         - Player 1 creates lobby
         - Player 2 joins lobby
 
 ### What needs to be made
- [ ] Add Lobby Management: Create a class to manage lobbies and handle the creation, joining, and removal of lobbies.
- [ ] Update the WebSocket Handler: Modify the MyHandler class to handle commands related to lobby management.
- [ ] Frontend Integration: Make sure frontend can create lobbies, display available lobbies, and allow players to join them. Main screen should have "Create Lobby" for Player 1 and "Join Lobby" for Player 2
---------------------------------------------------------------------
## Wednesday
I didn't make as much progress as I wanted to today, but I am still happy with where I ended. I had to somewhat revamp most of what I've done so far. Instead of everything lobby related being websockets, I shifted some to api endpoints and the fighting into websockets. Now the process looks like this:

- Create Lobby: Send a POST request to /api/lobby/create with lobbyId.
- Register and Join Lobby: Send a POST request to /api/lobby/registerAndJoin with lobbyId, playerName, attack, and health.
- Attack Command: Connect and use WebSockets to send a message with the command attack:attackerName;targetName.

# WEEK 2
# Tuesday
Well we hit a roadblock. My features do work but not from the live frontend to backend server. So now I have to redo the whole thing for endpoints. I will probably spend a couple hours tonight and hope everything will work :)
